name: test

on:
  push:
    branches:
      - "@express-zod-api/zod"
  pull_request:
    branches:
      - "@express-zod-api/zod"

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
        typescript: ["4.5", "4.6", "4.7", "4.8", "4.9"]
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn add typescript@${{ matrix.typescript }}
      - run: yarn build
      - run: yarn test


  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn prettier:check
      - run: yarn lint:check
